#!/bin/bash
#
# This aims to be a batch file to be used to create users and configure their group membership and pw info
# Class: TP01 - Linux Administration
# 
useradd -e `date +%D --date='2 years'` -g 1001 -u 1001 -s /bin/bash invite # création compte avec expiration PW 2 ans après création du compte. 
chage --maxdays 30 --mindays 7 invite # contraintes quant a l'expiration PW
passwd -e invite # -e pour forcer le changement de passwd au prochain login
groupadd -g 1001 invites
usermod -g invites

